In [137]:
import pandas as pd
import datetime as dt            #library for date management
import matplotlib.pyplot as plt  #library for plotting
import re 
import numpy as np
import re
from bs4 import BeautifulSoup
import unicodedata
import nltk
from gensim.parsing.preprocessing import remove_stopwords
import pkg_resources
from symspellpy.symspellpy import SymSpell

In [23]:
df_1 = pd.read_csv(r"dataset_food_posts_missing_2018.csv")
print('len combined: ' + str(len(df_1)))

df_2 = pd.read_csv(r"dataset_food_posts_missing_2019.csv")
print('len combined: ' + str(len(df_2)))

df_3 = pd.read_csv(r"dataset_food_posts_missing_2020.csv")
print('len combined: ' + str(len(df_3)))

df_4 = pd.read_csv(r"dataset_food_posts_missing_2021.csv")
print('len combined: ' + str(len(df_4)))

df_5 = pd.read_csv(r"dataset_food_posts_missing_2022.csv")
print('len combined: ' + str(len(df_5)))



df_combined =  pd.concat([df_1, df_2, df_3, df_4, df_5])
print('len combined: ' + str(len(df_combined)))

len combined: 3396
len combined: 3851
len combined: 5101
len combined: 3525
len combined: 877
len combined: 16750

In [138]:
df_combined = pd.read_csv('missing_data_from_dumps.csv')

In [142]:
df_combined = df_combined.drop(['Unnamed: 0', 'just_date'],axis=1)

In [143]:
df_combined.head()

                                               title             datetime
0  البقلاوه واسرار جمالها بابسط الطرق#حلويات سهله...  2019-01-31 00:01:15
1             [Homemade] Fruity Pebble Krispie Treat  2019-01-31 00:04:30
2  [Homemade] Pan-fried ricotta gnocchi with a ga...  2019-01-31 00:06:58
3                                              Yummy  2019-01-31 00:08:31
4                 [homemade] Chanko-nabe, sumo stew!  2019-01-31 00:09:11

In [144]:
import pkg_resources
from symspellpy.symspellpy import SymSpell, Verbosity
import numpy as np

In [145]:
df_food_posts_copy = df_combined[['datetime', 'title']].copy()

In [146]:
df_food_posts_copy.head()

              datetime                                              title
0  2019-01-31 00:01:15  البقلاوه واسرار جمالها بابسط الطرق#حلويات سهله...
1  2019-01-31 00:04:30             [Homemade] Fruity Pebble Krispie Treat
2  2019-01-31 00:06:58  [Homemade] Pan-fried ricotta gnocchi with a ga...
3  2019-01-31 00:08:31                                              Yummy
4  2019-01-31 00:09:11                 [homemade] Chanko-nabe, sumo stew!

In [147]:
df_food_posts_copy['preprocessed_title_1'] = df_food_posts_copy['title'].apply(lambda x: str(x).lower())

In [148]:
df_food_posts_copy.head()

,datetime,title,preprocessed_title_1
0,2019-01-31 00:01:15,البقلاوه واسرار جمالها بابسط الطرق#حلويات سهله...,البقلاوه واسرار جمالها بابسط الطرق#حلويات سهله...
1,2019-01-31 00:04:30,[Homemade] Fruity Pebble Krispie Treat,[homemade] fruity pebble krispie treat
2,2019-01-31 00:06:58,[Homemade] Pan-fried ricotta gnocchi with a ga...,[homemade] pan-fried ricotta gnocchi with a ga...
3,2019-01-31 00:08:31,Yummy,yummy
4,2019-01-31 00:09:11,"[homemade] Chanko-nabe, sumo stew!","[homemade] chanko-nabe, sumo stew!"

In [149]:
def remove_text_from_brackets(x):
    if x is not np.nan:  
        return re.sub(r"[\(\[].*?[\)\]]", "", x)
    return x

In [150]:
df_food_posts_copy['preprocessed_title'] = df_food_posts_copy['preprocessed_title_1'].apply(lambda x: remove_text_from_brackets(x))

In [151]:
df_food_posts_copy.head()

,datetime,title,preprocessed_title_1,preprocessed_title
0,2019-01-31 00:01:15,البقلاوه واسرار جمالها بابسط الطرق#حلويات سهله...,البقلاوه واسرار جمالها بابسط الطرق#حلويات سهله...,البقلاوه واسرار جمالها بابسط الطرق#حلويات سهله...
1,2019-01-31 00:04:30,[Homemade] Fruity Pebble Krispie Treat,[homemade] fruity pebble krispie treat,fruity pebble krispie treat
2,2019-01-31 00:06:58,[Homemade] Pan-fried ricotta gnocchi with a ga...,[homemade] pan-fried ricotta gnocchi with a ga...,pan-fried ricotta gnocchi with a garlic-saffo...
3,2019-01-31 00:08:31,Yummy,yummy,yummy
4,2019-01-31 00:09:11,"[homemade] Chanko-nabe, sumo stew!","[homemade] chanko-nabe, sumo stew!","chanko-nabe, sumo stew!"

In [152]:
len(df_food_posts_copy)

12663

In [153]:
df_food_posts_copy['preprocessed_title'] = df_food_posts_copy['preprocessed_title'].apply(lambda x: re.sub(r'(https|http)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , x))

In [154]:
df_food_posts_copy['preprocessed_title'] = df_food_posts_copy['preprocessed_title'].apply(lambda x: re.sub(r'[^\w]', ' ', x))

In [155]:
df_food_posts_copy['preprocessed_title'] = df_food_posts_copy['preprocessed_title'].apply(lambda x: re.sub('_', ' ', x))

In [156]:
df_food_posts_copy['preprocessed_title_no_stopwords'] = df_food_posts_copy['preprocessed_title'].apply(lambda x: remove_stopwords(x))

In [157]:
df_food_posts_copy.head()

,datetime,title,preprocessed_title_1,preprocessed_title,preprocessed_title_no_stopwords
0,2019-01-31 00:01:15,البقلاوه واسرار جمالها بابسط الطرق#حلويات سهله...,البقلاوه واسرار جمالها بابسط الطرق#حلويات سهله...,البقلاوه واسرار جمالها بابسط الطرق حلويات سهله...,البقلاوه واسرار جمالها بابسط الطرق حلويات سهله...
1,2019-01-31 00:04:30,[Homemade] Fruity Pebble Krispie Treat,[homemade] fruity pebble krispie treat,fruity pebble krispie treat,fruity pebble krispie treat
2,2019-01-31 00:06:58,[Homemade] Pan-fried ricotta gnocchi with a ga...,[homemade] pan-fried ricotta gnocchi with a ga...,pan fried ricotta gnocchi with a garlic saffo...,pan fried ricotta gnocchi garlic saffon cream ...
3,2019-01-31 00:08:31,Yummy,yummy,yummy,yummy
4,2019-01-31 00:09:11,"[homemade] Chanko-nabe, sumo stew!","[homemade] chanko-nabe, sumo stew!",chanko nabe sumo stew,chanko nabe sumo stew

In [158]:
def remove_non_english(text):
    text = re.sub("[^a-zA-Z0-9 ]+", "",text)
    return text

In [159]:
def remove_common_strings(x):
    strings = ['restaurant', 'food', 'breakfast', 'lunch', 'dinner', 'snack', 'homemade']
    if type(x) is str:
        for s in strings:
            if s in x:
                x = re.sub(s, '', x)
    return x

In [160]:
df_food_posts_copy['preprocessed_title'] = df_food_posts_copy['preprocessed_title'].apply(lambda x: remove_common_strings(x))

In [161]:
df_food_posts_copy['preprocessed_title'] = df_food_posts_copy['preprocessed_title'].apply(lambda x: remove_non_english(x))

In [162]:
df_food_posts_copy['preprocessed_title'] = df_food_posts_copy['preprocessed_title'].apply(lambda x: re.sub(' +', ' ', x))

In [163]:
df_food_posts_copy.head(20)

,datetime,title,preprocessed_title_1,preprocessed_title,preprocessed_title_no_stopwords
0,2019-01-31 00:01:15,البقلاوه واسرار جمالها بابسط الطرق#حلويات سهله...,البقلاوه واسرار جمالها بابسط الطرق#حلويات سهله...,,البقلاوه واسرار جمالها بابسط الطرق حلويات سهله...
1,2019-01-31 00:04:30,[Homemade] Fruity Pebble Krispie Treat,[homemade] fruity pebble krispie treat,fruity pebble krispie treat,fruity pebble krispie treat
2,2019-01-31 00:06:58,[Homemade] Pan-fried ricotta gnocchi with a ga...,[homemade] pan-fried ricotta gnocchi with a ga...,pan fried ricotta gnocchi with a garlic saffo...,pan fried ricotta gnocchi garlic saffon cream ...
3,2019-01-31 00:08:31,Yummy,yummy,yummy,yummy
4,2019-01-31 00:09:11,"[homemade] Chanko-nabe, sumo stew!","[homemade] chanko-nabe, sumo stew!",chanko nabe sumo stew,chanko nabe sumo stew
5,2019-01-31 00:14:46,"Homemade Lettuce Burger, Fries, &amp; Big Mac ...","homemade lettuce burger, fries, &amp; big mac ...",lettuce burger fries amp big mac sauce,homemade lettuce burger fries amp big mac sauce
6,2019-01-31 00:15:34,"[i ate] spider roll, girl rolls, spicy kani roll","[i ate] spider roll, girl rolls, spicy kani roll",spider roll girl rolls spicy kani roll,spider roll girl rolls spicy kani roll
7,2019-01-31 00:17:00,[Homemade] Macarons,[homemade] macarons,macarons,macarons
8,2019-01-31 00:17:06,تعالو شوفو سر توفر الذبده البلدي عندي #زبد طبي...,تعالو شوفو سر توفر الذبده البلدي عندي #زبد طبي...,,تعالو شوفو سر توفر الذبده البلدي عندي زبد طبيع...
9,2019-01-31 00:20:26,Tried my hand at ramen,tried my hand at ramen,tried my hand at ramen,tried hand ramen
10,2019-01-31 00:20:27,[I ate] ryebread cheddar cheese &amp; smoked h...,[i ate] ryebread cheddar cheese &amp; smoked h...,ryebread cheddar cheese amp smoked ham toast ...,ryebread cheddar cheese amp smoked ham toast v...
11,2019-01-31 00:23:16,[i made] these yummy pickles,[i made] these yummy pickles,these yummy pickles,yummy pickles
12,2019-01-31 00:25:47,"[Homemade] Lettuce Burger, Fries, &amp; Big Ma...","[homemade] lettuce burger, fries, &amp; big ma...",lettuce burger fries amp big mac sauce,lettuce burger fries amp big mac sauce
13,2019-01-31 00:30:52,Nutella drip cake I made today for my sons 15t...,nutella drip cake i made today for my sons 15t...,nutella drip cake i made today for my sons 15t...,nutella drip cake today sons 15th birthday
14,2019-01-31 00:31:25,Yeet,yeet,yeet,yeet
15,2019-01-31 00:31:59,[I ate] some bomb El Salvadoran food: steak an...,[i ate] some bomb el salvadoran food: steak an...,some bomb el salvadoran steak and pupusas,bomb el salvadoran food steak pupusas
16,2019-01-31 00:36:13,[Homemade] Huli Huli Chicken,[homemade] huli huli chicken,huli huli chicken,huli huli chicken
17,2019-01-31 00:36:15,[I devoured] street tacos and a gordita,[i devoured] street tacos and a gordita,street tacos and a gordita,street tacos gordita
18,2019-01-31 00:38:31,[I ate] street tacos and a gordita,[i ate] street tacos and a gordita,street tacos and a gordita,street tacos gordita
19,2019-01-31 00:39:23,"[I Ate] Kalua Pork, Teriyaki Pork, Steamed Ric...","[i ate] kalua pork, teriyaki pork, steamed ric...",kalua pork teriyaki pork steamed rice amp mac...,kalua pork teriyaki pork steamed rice amp maca...

In [168]:
len(df_food_posts_copy[df_food_posts_copy['preprocessed_title'] == ''])

0

In [169]:
len(df_food_posts_copy[df_food_posts_copy['preprocessed_title'] == ' '])

0

In [166]:
df_food_posts_copy = df_food_posts_copy[df_food_posts_copy['preprocessed_title'] != '']

In [167]:
df_food_posts_copy = df_food_posts_copy[df_food_posts_copy['preprocessed_title'] != ' ']

In [170]:
df_food_posts_copy.to_csv('food_posts_missing_preprocessed_dump.csv')

In [171]:
df_food_posts = pd.read_csv(r'food_posts_missing_preprocessed_dump.csv')

In [172]:
len(df_food_posts)

12566

In [173]:
nutritional_information_usda = pd.read_csv('nutritional_database_combined_20_05.csv')

In [174]:
len(nutritional_information_usda)

15035

In [175]:
nutritional_information_usda.head()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,description,food_class,food_category,serving_size,serving_size_unit,calories_serving_size,calories_100g,...,cholesterol_unit,carbohydrates_serving_size,carbohydrates_100g,carbohydrates_unit,fiber_serving_size,fiber_100g,fiber_unit,protein_calories,fat_calories,carb_calories
0,0,0,0,"Milk, human",Survey,Human milk,100,g,NaN,70.0,...,mg,NaN,6.89,g,NaN,0.0,g,4.12,4.473,27.56
1,1,1,0,"Milk, NFS",Survey,"Milk, reduced fat",100,g,NaN,51.0,...,mg,NaN,4.87,g,NaN,0.0,g,13.36,0.585,19.48
2,2,2,0,"Milk, whole",Survey,"Milk, whole",100,g,NaN,60.0,...,mg,NaN,4.67,g,NaN,0.0,g,13.12,0.972,18.68
3,3,3,0,"Milk, low sodium, whole",Survey,"Milk, whole",100,g,NaN,61.0,...,mg,NaN,4.46,g,NaN,0.0,g,12.40,1.152,17.84
4,4,4,0,"Milk, calcium fortified, whole",Survey,"Milk, whole",100,g,NaN,60.0,...,mg,NaN,4.67,g,NaN,0.0,g,13.12,0.972,18.68

In [176]:
nutritional_information_usda['description'] = nutritional_information_usda['description'].apply(lambda x: re.sub(r'[^\w]', ' ', x))

In [177]:
nutritional_information_usda['description'] = nutritional_information_usda['description'].apply(lambda x: re.sub('_', ' ', x))

In [178]:
nutritional_information_usda['description'] = nutritional_information_usda['description'].apply(lambda x: re.sub(' +', ' ', x))

In [179]:
nutritional_information_usda['description'] = nutritional_information_usda['description'].apply(lambda x: x.lower())

In [180]:
nutritional_information_usda.head()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,description,food_class,food_category,serving_size,serving_size_unit,calories_serving_size,calories_100g,...,cholesterol_unit,carbohydrates_serving_size,carbohydrates_100g,carbohydrates_unit,fiber_serving_size,fiber_100g,fiber_unit,protein_calories,fat_calories,carb_calories
0,0,0,0,milk human,Survey,Human milk,100,g,NaN,70.0,...,mg,NaN,6.89,g,NaN,0.0,g,4.12,4.473,27.56
1,1,1,0,milk nfs,Survey,"Milk, reduced fat",100,g,NaN,51.0,...,mg,NaN,4.87,g,NaN,0.0,g,13.36,0.585,19.48
2,2,2,0,milk whole,Survey,"Milk, whole",100,g,NaN,60.0,...,mg,NaN,4.67,g,NaN,0.0,g,13.12,0.972,18.68
3,3,3,0,milk low sodium whole,Survey,"Milk, whole",100,g,NaN,61.0,...,mg,NaN,4.46,g,NaN,0.0,g,12.40,1.152,17.84
4,4,4,0,milk calcium fortified whole,Survey,"Milk, whole",100,g,NaN,60.0,...,mg,NaN,4.67,g,NaN,0.0,g,13.12,0.972,18.68

In [181]:
words = list(nutritional_information_usda['description'])

In [182]:
len(words)

15035

In [183]:
df_food_titles_similar_ngram_2 = pd.DataFrame(columns = ['food_post_title', 'food_post_date', 'closest_match_from_usda', 
                                                        'calories_ngrams', 'protein_ngrams', 'fat_ngrams', 'sugar_ngrams', 
                                                        'carbohydrates_ngrams', 'sodium_ngrams', 'cholesterol_ngrams', 
                                                        'fiber_ngrams', 'protein_calories', 'fat_calories', 
                                                         'carbohydrates_calories'])

In [184]:
for index, row in df_food_posts.iterrows():
    if index%500==0:
        print(index)
    # Create empty variables, where we will store nutritional information
    counter, calories_val, protein_val, fat_val, sugar_val, carb_val, sodium_val, choles_val, fiber_val = 0,0,0,0,0,0,0,0,0
    protein_calories, fat_calories, carbohydrates_calories = 0,0,0
    
    # Create empty lists to store matching titles and their indexes (from the usda file)
    title_matches, ind_list = [], []
    if type(row['preprocessed_title']) is str:
        tmp_title = ' '.join([w for w in row['preprocessed_title'].split() if len(w)>1])

        found_match = False
        n = len(tmp_title.split(' '))
        # For each entry loop through the list of ngrams
        while tmp_title != '':
            #print('tmp_title: ' + tmp_title)
            if found_match and len(matching_words) > 0:
                n = len(tmp_title.split(' '))
                found_match = False
            #print('n: '+ str(n))
            if n<1:
                break
            new_list = []
            grams = ngrams(tmp_title.split(), n)
            for g in grams:
                new_list.append(' '.join(list(g)))
            #print('new_list: ')
            #print(new_list)
            
            for r in new_list: 
                #print('r: '+ r)
                new_title=''

                for ind, w in enumerate(words):
                    # If match for ngram found append the title of match, index and add nutritional values
                    if re.search(r, w):
                        found_match = True
                        title_matches.append(w)
                        new_title=new_title+w
                        ind_list.append(ind)
                        # Increase the counter so we can compute the average value in the end
                        counter+=1
                        
                        # Find how much of the title matches

                        if not pd.isnull(nutritional_information_usda.iloc[ind]['calories_100g']):
                            calories_val+=nutritional_information_usda.iloc[ind]['calories_100g']

                        if not pd.isnull(nutritional_information_usda.iloc[ind]['protein_100g']):
                            protein_val+=nutritional_information_usda.iloc[ind]['protein_100g']

                        if not pd.isnull(nutritional_information_usda.iloc[ind]['fat_100g']):
                            fat_val+=nutritional_information_usda.iloc[ind]['fat_100g']

                        if not pd.isnull(nutritional_information_usda.iloc[ind]['sugar_100g']):
                            sugar_val+=nutritional_information_usda.iloc[ind]['sugar_100g']

                        if not pd.isnull(nutritional_information_usda.iloc[ind]['carbohydrates_100g']):
                            carb_val+=nutritional_information_usda.iloc[ind]['carbohydrates_100g']

                        if not pd.isnull(nutritional_information_usda.iloc[ind]['sodium_100g']):
                            sodium_val+=nutritional_information_usda.iloc[ind]['sodium_100g'] 

                        if not pd.isnull(nutritional_information_usda.iloc[ind]['cholesterol_100g']):
                            choles_val+=nutritional_information_usda.iloc[ind]['cholesterol_100g']

                        if not pd.isnull(nutritional_information_usda.iloc[ind]['fiber_100g']):
                            fiber_val+=nutritional_information_usda.iloc[ind]['fiber_100g']

                        # calories:
                        if not pd.isnull(nutritional_information_usda.iloc[ind]['protein_calories']):
                            protein_calories+=nutritional_information_usda.iloc[ind]['protein_calories']

                        if not pd.isnull(nutritional_information_usda.iloc[ind]['fat_calories']):
                            fat_calories+=nutritional_information_usda.iloc[ind]['fat_calories']

                        if not pd.isnull(nutritional_information_usda.iloc[ind]['carb_calories']):
                            carbohydrates_calories+=nutritional_information_usda.iloc[ind]['carb_calories']
                        
                        if counter>30:
                            break

            t1 = set(' '.join(new_list).lower().split(" "))
            t2 = set(re.split('; |, | |\n', new_title.lower()))
            #print('t1: ' + str(t1))
            #print('t2: ' + str(t2))
            matching_words = list(t1&t2)
            matching_words = [x for x in matching_words if x and x != ' ']
            #print('matching words: ' + str(matching_words))
            #print('len of matching words: ' + str(len(matching_words)))

            for mw in matching_words:
                #print('mw: '+ mw)
                tmp_title = tmp_title.replace(mw, '')
            tmp_title = ' '.join(tmp_title.split())
            

            if found_match and len(matching_words) == 0 and n==1:
                break
            if not found_match or len(matching_words) == 0:
                n=n-1

    # compute average calories
    if counter > 0:
        calories_val=round(calories_val/counter, 2)
        protein_val=round(protein_val/counter, 2)
        fat_val=round(fat_val/counter, 2)
        sugar_val=round(sugar_val/counter, 2)
        carb_val=round(carb_val/counter, 2)
        sodium_val=round(sodium_val/counter, 2)
        choles_val=round(choles_val/counter, 2)
        fiber_val=round(fiber_val/counter, 2)
        fat_calories=round(fat_calories/counter, 2)
        protein_calories=round(protein_calories/counter, 2)
        carbohydrates_calories=round(carbohydrates_calories/counter, 2)
    
    df_new_row = pd.DataFrame({'food_post_title': row['preprocessed_title'], 'food_post_date': row['datetime'],
                              'closest_match_from_usda':[title_matches], 'index_of_usda_in_json': [ind_list],
                               'calories_ngrams': [calories_val], 'protein_ngrams': [protein_val], 
                               'fat_ngrams': [fat_val], 'sugar_ngrams': [sugar_val], 
                               'carbohydrates_ngrams': [carb_val], 'sodium_ngrams': [sodium_val], 
                               'cholesterol_ngrams': [choles_val], 'fiber_ngrams': [fiber_val],
                               'protein_calories': [protein_calories], 'fat_calories': [fat_calories], 
                               'carbohydrates_calories': [carbohydrates_calories]})
    
    df_food_titles_similar_ngram_2 = pd.concat([df_food_titles_similar_ngram_2, df_new_row])

0
500
1000
1500
2000
2500
3000
3500
4000
4500
5000
5500
6000
6500
7000
7500
8000
8500
9000
9500
10000
10500
11000
11500
12000
12500

In [185]:
df_food_titles_similar_ngram_2.head()

,food_post_title,food_post_date,closest_match_from_usda,calories_ngrams,protein_ngrams,fat_ngrams,sugar_ngrams,carbohydrates_ngrams,sodium_ngrams,cholesterol_ngrams,fiber_ngrams,protein_calories,fat_calories,carbohydrates_calories,index_of_usda_in_json
0,fruity pebble krispie treat,2019-01-31 00:04:30,"[cereal post fruity pebbles , cereals ready to...",396.29,4.32,1.05,33.26,85.79,500.61,0.22,1.03,17.26,9.49,343.16,"[4228, 11216, 4227, 4228, 4262, 11216, 12572, ..."
0,pan fried ricotta gnocchi with a garlic saffo...,2019-01-31 00:06:58,[potatoes hash brown refrigerated prepared pan...,249.1,20.91,4.7,1.27,7.48,305.95,262.1,0.46,87.98,42.16,29.84,"[7176, 7283, 7439, 7453, 7454, 7455, 7458, 746..."
0,yummy,2019-01-31 00:08:31,[],0,0,0,0,0,0,0,0,0,0,0,[]
0,chanko nabe sumo stew,2019-01-31 00:09:11,"[beef stew meat cooked ns as to fat eaten, bee...",192.55,23.27,1.66,0.42,0.96,471.0,87.97,0.21,93.08,14.92,3.82,"[691, 692, 693, 744, 745, 746, 893, 917, 918, ..."
0,lettuce burger fries amp big mac sauce,2019-01-31 00:14:46,"[mcdonald s big mac without big mac sauce , ch...",152.62,10.62,1.42,2.34,12.69,374.5,43.47,1.09,42.5,12.75,50.77,"[11638, 2174, 2175, 2176, 2177, 2178, 2179, 21..."

In [186]:
df_food_titles_similar_ngram_2.to_csv('food_matches_missing_from_dumps.csv')

In [205]:
df_combined = pd.read_csv('food_matches_missing.csv')

In [204]:
df_combined_1 = pd.read_csv('upgraded_results_for_timeseries_analysis.csv')

In [207]:
df_combined_1 = df_combined_1.drop(['Unnamed: 0','calories_ngrams', 'closest_match_from_usda_list', 'index_of_usda_in_json_list'], axis=1)

In [206]:
df_combined_2 = pd.read_csv('food_matches_missing_from_dumps.csv')

In [208]:
df_combined_2 = df_combined_2.rename(columns = {'calories_ngrams':'calories', 'protein_ngrams':'protein', 'fat_ngrams':'fat', 'sugar_ngrams':'sugar', 'carbohydrates_ngrams':'carbohydrates', 'sodium_ngrams':'sodium', 'cholesterol_ngrams':'cholesterol', 'fiber_ngrams':'fiber', 'protein_calories':'protein_cals', 'fat_calories':'fat_cals', 'carbohydrates_calories':'carb_cals', })

In [209]:
df_combined = df_combined.rename(columns = {'calories_ngrams':'calories', 'protein_ngrams':'protein', 'fat_ngrams':'fat', 'sugar_ngrams':'sugar', 'carbohydrates_ngrams':'carbohydrates', 'sodium_ngrams':'sodium', 'cholesterol_ngrams':'cholesterol', 'fiber_ngrams':'fiber', 'protein_calories':'protein_cals', 'fat_calories':'fat_cals', 'carbohydrates_calories':'carb_cals', })

In [212]:
df_combined_2 = df_combined_2.drop(['Unnamed: 0'], axis=1)

In [210]:
df_combined = df_combined.drop(['Unnamed: 0'], axis=1)

In [214]:
df_combined.head()

,food_post_title,food_post_date,closest_match_from_usda,calories,protein,fat,sugar,carbohydrates,sodium,cholesterol,fiber,protein_cals,fat_cals,carb_cals,index_of_usda_in_json
0,cheeseburger with minced garlic and jalapeo c...,2018-03-31 00:02:47,['roast beef submarine sandwich with cheese le...,241.26,12.27,2.76,4.73,18.88,529.31,35.67,1.15,49.09,24.86,75.52,"[2315, 2373, 2379, 2381, 2383, 2420, 10359, 55..."
1,torta di pera e ciaccolato,2018-03-31 00:14:11,['bread pound cake type pan de torta salvadora...,217.68,3.65,8.18,7.24,10.61,414.97,21.10,0.36,14.59,73.64,42.44,"[7098, 3, 73, 74, 75, 76, 77, 78, 79, 279, 280..."
2,delicious cinnamon buns twiced proved icing w...,2018-03-31 00:17:04,['pie cherry made with cream cheese and sour c...,184.37,8.49,2.07,5.81,17.22,337.42,44.19,0.75,33.97,18.61,68.87,"[3590, 7511, 1676, 1679, 1714, 1730, 1746, 175..."
3,louisiana crawfish boil,2018-03-31 00:19:08,['beef pot roast braised or boiled ns as to fa...,153.58,11.32,1.37,1.26,12.40,298.77,63.26,1.29,45.30,12.35,49.59,"[688, 689, 690, 827, 848, 1572, 1583, 1598, 16..."
4,whole s or 99 cents store taste test,2018-03-31 00:23:21,"['milk whole', 'milk low sodium whole', 'milk ...",89.70,4.62,0.22,7.43,10.24,67.03,25.69,0.51,18.49,1.99,40.96,"[2, 3, 4, 15, 19, 21, 23, 27, 48, 52, 56, 60, ..."

In [213]:
df_combined_2.head()

,food_post_title,food_post_date,closest_match_from_usda,calories,protein,fat,sugar,carbohydrates,sodium,cholesterol,fiber,protein_cals,fat_cals,carb_cals,index_of_usda_in_json
0,fruity pebble krispie treat,2019-01-31 00:04:30,"['cereal post fruity pebbles ', 'cereals ready...",396.29,4.32,1.05,33.26,85.79,500.61,0.22,1.03,17.26,9.49,343.16,"[4228, 11216, 4227, 4228, 4262, 11216, 12572, ..."
1,pan fried ricotta gnocchi with a garlic saffo...,2019-01-31 00:06:58,['potatoes hash brown refrigerated prepared pa...,249.10,20.91,4.70,1.27,7.48,305.95,262.10,0.46,87.98,42.16,29.84,"[7176, 7283, 7439, 7453, 7454, 7455, 7458, 746..."
2,yummy,2019-01-31 00:08:31,[],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,[]
3,chanko nabe sumo stew,2019-01-31 00:09:11,"['beef stew meat cooked ns as to fat eaten', '...",192.55,23.27,1.66,0.42,0.96,471.00,87.97,0.21,93.08,14.92,3.82,"[691, 692, 693, 744, 745, 746, 893, 917, 918, ..."
4,lettuce burger fries amp big mac sauce,2019-01-31 00:14:46,"['mcdonald s big mac without big mac sauce ', ...",152.62,10.62,1.42,2.34,12.69,374.50,43.47,1.09,42.50,12.75,50.77,"[11638, 2174, 2175, 2176, 2177, 2178, 2179, 21..."

In [215]:
df_combined_1.head()

,food_post_title,food_post_date,closest_match_from_usda,protein,fat,sugar,carbohydrates,sodium,cholesterol,fiber,protein_cals,fat_cals,carb_cals,index_of_usda_in_json,calories
0,clean fridge frittata,2019-09-29 15:42:15,[],0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,[],0.000000
1,poached eggs bacon mushrooms toasted sourdough...,2019-09-29 16:01:41,"['Barracuda steamed or poached', 'Carp steam...",19.196491,1.464982,1.004912,7.418070,496.701754,82.385965,0.438596,76.864912,13.185933,29.668295,"[1263, 1270, 1288, 1305, 1315, 1317, 1336, 134...",183.433158
2,spicy miso tsukemen,2019-09-29 16:02:26,"['Soybean soup miso broth', 'Cheese goat se...",12.035000,15.212500,0.505000,1.295000,512.500000,41.500000,0.200000,51.056000,133.783500,5.172200,"[2961, 13004]",198.145000
3,single serve sugar baby watermelon,2019-09-29 16:02:31,['Fast foods cheeseburger single large patt...,8.543636,2.021864,10.293333,18.650227,280.454545,22.590909,0.962791,34.370636,17.456117,74.363318,"[9865, 10261, 10262, 10263, 10264, 10265, 1028...",183.341136
4,chocolate chip cookie dough cheesecake,2019-09-29 16:03:06,"['Muffin chocolate chip', 'Cookie chocolate ...",7.395870,6.511587,26.244000,51.198478,464.239130,19.444444,1.823256,28.762870,57.230130,201.057391,"[3356, 3460, 3461, 3462, 3463, 3494, 3504, 354...",386.065435

In [217]:
len(df_combined)

16615

In [218]:
len(df_combined_1)

561550

In [219]:
len(df_combined_2)

12566

In [220]:
df_combined_3 =  pd.concat([df_combined, df_combined_1, df_combined_2])

In [221]:
len(df_combined_3)

590731

In [222]:
df_combined_3.head()

,food_post_title,food_post_date,closest_match_from_usda,calories,protein,fat,sugar,carbohydrates,sodium,cholesterol,fiber,protein_cals,fat_cals,carb_cals,index_of_usda_in_json
0,cheeseburger with minced garlic and jalapeo c...,2018-03-31 00:02:47,['roast beef submarine sandwich with cheese le...,241.26,12.27,2.76,4.73,18.88,529.31,35.67,1.15,49.09,24.86,75.52,"[2315, 2373, 2379, 2381, 2383, 2420, 10359, 55..."
1,torta di pera e ciaccolato,2018-03-31 00:14:11,['bread pound cake type pan de torta salvadora...,217.68,3.65,8.18,7.24,10.61,414.97,21.10,0.36,14.59,73.64,42.44,"[7098, 3, 73, 74, 75, 76, 77, 78, 79, 279, 280..."
2,delicious cinnamon buns twiced proved icing w...,2018-03-31 00:17:04,['pie cherry made with cream cheese and sour c...,184.37,8.49,2.07,5.81,17.22,337.42,44.19,0.75,33.97,18.61,68.87,"[3590, 7511, 1676, 1679, 1714, 1730, 1746, 175..."
3,louisiana crawfish boil,2018-03-31 00:19:08,['beef pot roast braised or boiled ns as to fa...,153.58,11.32,1.37,1.26,12.40,298.77,63.26,1.29,45.30,12.35,49.59,"[688, 689, 690, 827, 848, 1572, 1583, 1598, 16..."
4,whole s or 99 cents store taste test,2018-03-31 00:23:21,"['milk whole', 'milk low sodium whole', 'milk ...",89.70,4.62,0.22,7.43,10.24,67.03,25.69,0.51,18.49,1.99,40.96,"[2, 3, 4, 15, 19, 21, 23, 27, 48, 52, 56, 60, ..."

In [225]:
df_combined_3.iloc[-1]

food_post_title                                       honey cake aka medovik
food_post_date                                           2021-04-13 23:59:08
closest_match_from_usda    ['almonds honey roasted', 'cashews honey roast...
calories                                                              396.61
protein                                                                 8.12
fat                                                                     6.65
sugar                                                                  21.88
carbohydrates                                                          55.97
sodium                                                                430.27
cholesterol                                                             8.82
fiber                                                                   5.45
protein_cals                                                           32.33
fat_cals                                                               59.85
carb_cals                                                             223.77
index_of_usda_in_json      [3003, 3010, 3023, 3032, 3037, 3043, 3044, 365...
Name: 12565, dtype: object

In [226]:
df_combined_3.to_csv('upgraded_results_for_timeseries_analysis_with_dumps_and_missing_data.csv')

In [202]:
df_combined_4 = pd.read_csv('food_matches_missing.csv')

In [ ]:
df_combined_4